import numpy
def stdev_ddof_0(array: numpy.ndarray)-> int:

    ...
def stdev_ddof_1(array: numpy.ndarray)-> int:

    ...
def fast_std(array: numpy.ndarray)-> int:

    ...
def fast_std_clamp(array: numpy.ndarray)-> int:

    ...
def area_contrast(array: numpy.ndarray)-> int:

    ...
